env:
  browser: true
  es2021: true
extends:
  - airbnb
  - airbnb/hooks
  - plugin:react/recommended
  - plugin:react/jsx-runtime
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 'latest'
  sourceType: module
settings:
  react:
    version: 'detect'
  'import/resolver':
    node:
      extensions: ['.js', '.jsx']
rules:
  linebreak-style: ['error', 'unix']
  semi: ['error', 'always']
  'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx'] }]
  'react/react-in-jsx-scope': 'off'
  'react/prop-types': 'off'
  'no-unused-vars':
    ['error', { varsIgnorePattern: '^_', argsIgnorePattern: '^_' }]
  'import/prefer-default-export': 'off'
  'import/no-extraneous-dependencies': ['error', { devDependencies: true }]
  'import/extensions':
    ['error', 'ignorePackages', { js: 'never', jsx: 'never' }]
  'no-console': 'warn'
  'no-param-reassign': ['error', { props: false }]
  'comma-dangle': ['error', 'only-multiline']
  'arrow-body-style': 'off'
  'operator-linebreak': 'off'
  'object-curly-newline': 'off'
